spring:
  profiles:
    active: dev
  jackson:
    serialization:
      indent-output: true
      
    
server:
  port: 8011
  
#logging:
#  config: classpath:logbackup.xml
#  path: /javacode/javaee/zhilu-device/log
  
  