#database  pool config
# Number of ms to wait before throwing an exception if no connection is available.
#spring.datasource.tomcat.max-wait=10000
# Maximum number of active connections that can be allocated from this pool at the same time.
#spring.datasource.tomcat.max-active=300
# Validate the connection before borrowing it from the pool.
#spring.datasource.tomcat.test-on-borrow=true
# initial pool size
#spring.datasource.tomcat.initial-size=20

#必须加?zeroDateTimeBehavior=convertToNull否则会报错
#Cannot convert '0000-00-00 00:00:00' to TIMESTAMP

#datasource
spring:
  datasource: 
    url:  jdbc:mysql://192.168.10.9:3306/mia_iot?zeroDateTimeBehavior=convertToNull    
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    tomcat:
      initial-size: 20
      max-wait: 6000
      max-active: 300
      test-on-borrow: true
      


 

      
    
    
